<?php
echo "<div class=\"atp\" style=\"width:90%;padding-left:20px;\"><br><br>";
echo "<div style=\"font-family:verdana;font-weight:lighter;font-size:small;\"><p style=\"font-family:verdana;font-weight:bold;font-size:small;\"> What is PopAbooK.com ? </p> <p>PopAbooK.com is an online book store. Just like your local BookStore you can buy new and used books on PopAbooK.com</p></div>";
echo "<div style=\"font-family:verdana;font-weight:lighter;font-size:small;\"><p style=\"font-family:verdana;font-weight:bold;font-size:small;\"> What is Your Account ? </p> <p>Your Account shows your Shipping Address and Orders and your sales account(incase you sell the used books)</p></div>";
echo "<div style=\"font-family:verdana;font-weight:lighter;font-size:small;\"><p style=\"font-family:verdana;font-weight:bold;font-size:small;\"> What is the payment method ?</p> <p> We use EBS Payment Gateway and we accept payments online through credit cards, debit cards, internet banking and cash cards.</p></div>";
echo "<div style=\"font-family:verdana;font-weight:lighter;font-size:small;\"><p style=\"font-family:verdana;font-weight:bold;font-size:small;\"> What is your Shipping Policy ?</p> <p> We send books using Courier Service, in case courier service is not available in your area, we use registered India Post</p></div>";


echo "<div style=\"font-family:verdana;font-weight:lighter;font-size:small;\"><p style=\"font-family:verdana;font-weight:bold;font-size:small;\"> What if books received are damaged ?</p> <p> We take atmost care and use quality packing to ensure books are not damaged. Incase they are damaged please return damaged books to the Address mentioned in Contact Us link. We will send new books or refund the money within 5 days.</p></div>";
echo "<div style=\"font-family:verdana;font-weight:lighter;font-size:small;\"><p style=\"font-family:verdana;font-weight:bold;font-size:small;\"> What about information security ?</p> <p> We support both HTTP and HTTPS so all information [search string, shipping cart, shipping address, login data] exchanged between the browser and our servers is secure when HTTPS is used. SSL certificate provided by GoDaddy.com Inc</p></div>";

echo "<a name=\"usedbooks\"> <div style=\"font-family:verdana;font-weight:lighter;font-size:small;\"><p style=\"font-family:verdana;font-weight:bold;font-size:small;\"> How to Sell/Buy Used Books?</p> <p> <b>Sell Used Books</b><br><br>At PopAbooK.com you can sell your used books. Listing Books is absolutely FREE!!! Go ahead and list your books<br><ul><li>Enter the details of the book you want to sell. This can done through Your Account --> Sell Books.</li><li>On receiving an order, PopAbooK.com will collect books from your home/office, verify, pack  and  Ship the books to customer. You dont have to worry about packing and shipping.</li><li>With 7 days you will receive a check from PopAbooK.com for the sale.</li><li>***This facility (selling used books) is currently available only in Bangalore</li></ul> If your book is returned by the buyer PopAbooK.com will stock your book for potential sales with your permission.<br><br>PopAbooK.com charges commision on each sale. <br> Its Rs. 30 or 20% of sale price whatever is higher.<br> Example <br>Used Book at Rs. 300 <br>Commission Rs.60 <br> Seller Receives a check of Rs. 240 <br>PopAbooK.com has the right to prosecute if pirated copies of books are put on sale. <br><br><b>Buy Used Books</b> <br><br>Click Used Books link on search results page to view all the used books available. You can choose the right book for you based on book condition and price. Used books are procured from seller, verified, packed and shipped by PopAbooK.com<br>This facility (buying used books)is available at all locations in India<br></p></div> </a>";


echo "</div>";
?>

